In [1]:
import numpy as np

In [46]:
# one dimensional array

array = np.array([1,2,3])
print(array)

[1 2 3]


In [47]:
# two dimensional array

array = np.array([[1,2],[2,3]])
print(array)

[[1 2]
 [2 3]]


In [48]:
# How to create an empty and a full NumPy array?

empty_array = np.empty([1,2,3])
print(empty_array)


[[[0. 0. 0.]
  [0. 0. 0.]]]


In [49]:
empty_array = np.zeros([1,2,3])
print(empty_array)

[[[0. 0. 0.]
  [0. 0. 0.]]]


In [50]:
empty_array = np.full([2,3],4)
print(empty_array)

[[4 4 4]
 [4 4 4]]


In [51]:
# Create a Numpy array filled with all zeros | Python

zero_array = np.zeros([1,2,3])
print(zero_array)

[[[0. 0. 0.]
  [0. 0. 0.]]]


In [52]:
# Create a Numpy array filled with all ones

one_array = np.ones([2,3])
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [53]:
# Check whether a Numpy array contains a specified row

arr = np.array([[1,2,3,4,5], 
       [6,7,8,9,10], 
       [11,12,13,14,15], 
       [16,17,18,19,20]])
print(arr)

print([1, 2, 3, 4, 5] in arr.tolist())
print([16, 17, 20, 19, 18] in arr.tolist())
print([3, 2, 5, -4, 5] in arr.tolist())
print([11, 12, 13, 14, 15] in arr.tolist())


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True
False
False
True


In [54]:
# How to Remove rows in Numpy array that contains non-numeric values?

arr = np.array([[1,2,3],[4,np.nan,np.nan],[5,6,7],[8,9,10]])

print(arr[~np.isnan(arr).any(axis=1)])

filterd_array = arr[~np.isnan(arr).any(axis=1)]
print(filterd_array)



[[ 1.  2.  3.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[ 1.  2.  3.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [55]:
# Remove single-dimensional entries from the shape of an array

arr = np.array([[[2,3,4],[5,6,7],[1,8,9]]])
print(arr)

# a = np.squeeze(arr)
# print(a)
print(np.squeeze(arr))

print(arr.shape)

[[[2 3 4]
  [5 6 7]
  [1 8 9]]]
[[2 3 4]
 [5 6 7]
 [1 8 9]]
(1, 3, 3)


In [56]:
# Find the number of occurrences of a sequence in a NumPy array

Arr = np.array([[2,8,9,4],
       [9,4,9,4],
       [4,5,9,7],
       [2,9,4,3]])
print(Arr)

a = repr(Arr).count("9, 4")
print(a)


[[2 8 9 4]
 [9 4 9 4]
 [4 5 9 7]
 [2 9 4 3]]
4


In [57]:
# Find the most frequent value in a NumPy array

x = np.array([1,2,3,4,5,1,2,1,1,1])
list = x.tolist()
print(f"list : {list}")

a = max(set(list), key=list.count)
print(a)


list : [1, 2, 3, 4, 5, 1, 2, 1, 1, 1]
1


In [58]:
# Combining a one and a two-dimensional NumPy Array 

one_dimen = np.arange(5)
print(one_dimen)

two_dimen = np.arange(10).reshape(2,5)
print(two_dimen)

for i,j in np.nditer([one_dimen,two_dimen]):
    print(i,j)

[0 1 2 3 4]
[[0 1 2 3 4]
 [5 6 7 8 9]]
0 0
1 1
2 2
3 3
4 4
0 5
1 6
2 7
3 8
4 9


In [59]:
# How to build an array of all combinations of two NumPy arrays?

array_1 = np.array([1, 2])
array_2 = np.array([4, 6])

merge_array = np.concatenate((array_1,array_2))
print(merge_array)

merged_array = array_1 + array_2
print(merged_array)

comb_array = np.array(np.meshgrid(array_1, array_2)).T.reshape(-1, 2)
print(comb_array)

[1 2 4 6]
[5 8]
[[1 4]
 [1 6]
 [2 4]
 [2 6]]


In [60]:
# How to add a border around a NumPy array?

array = np.ones((2,2))
print(array)

array = np.pad(array, pad_width=1, mode='constant',constant_values=0)
print(array)
  

[[1. 1.]
 [1. 1.]]
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [61]:
array = np.zeros((3,3))
print(array)

array = np.pad(array,pad_width = 1, mode = "constant", constant_values = 2)
print(array)

print(array.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2. 2. 2. 2. 2.]
 [2. 0. 0. 0. 2.]
 [2. 0. 0. 0. 2.]
 [2. 0. 0. 0. 2.]
 [2. 2. 2. 2. 2.]]
(5, 5)


In [62]:
# How to compare two NumPy arrays?

array_1 = np.array([[1, 2], [3, 4]])
array_2 = np.array([[1, 2], [3, 4]])

compare_array = array_1 == array_2
print(compare_array)

print(compare_array.all())

if np.array_equal(array_1,array_2):
    print("equal")
else:
    print("not equal")

[[ True  True]
 [ True  True]]
True
equal


In [63]:
# How to check whether specified values are present in NumPy array?

array = np.array([[2, 3, 0],
                    [4, 1, 6]])
# lst = array.tolist()
# print(f"List : {lst}")

print(0  in array)
  

List : [[2, 3, 0], [4, 1, 6]]
True
wrong


In [70]:
# How to get all 2D diagonals of a 3D NumPy array?

array = np.arange(2*4*5).reshape(2,4,5)
print(array, "\n")


diag_arr = np.diagonal(array,axis1 = 1,axis2 = 2)
print(diag_arr)
  

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]] 

[[ 0  6 12 18]
 [20 26 32 38]]


In [3]:
array = np.arange(2*6*5).reshape(2,6,5)
print(array, "\n")

diagonal_array = np.diagonal(array,axis1 = 1,axis2 = 2)
print(diagonal_array)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]] 

[[ 0  6 12 18 24]
 [30 36 42 48 54]]


In [74]:
# Flatten a Matrix in Python using NumPy

gfg = np.array([[2, 3], [4, 5]])

flat_array = gfg.flatten()
print(flat_array)

[2 3 4 5]


In [79]:
# Python | Flatten a 2d numpy array into 1d array

array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("original array:", array)

flat_array = array.flatten()
print(flat_array)
print(type(flat_array))


original array: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'numpy.ndarray'>


In [84]:
# Move axes of an array to new positions

array = np.array([1,2,3,4])
array = np.zeros([1,2,3,4])

gfg = np.moveaxis(array, 0, -1).shape
print(gfg)

(2, 3, 4, 1)


In [85]:
gfg = np.moveaxis(array,1,2).shape
print(gfg)

(1, 3, 2, 4)


In [87]:
gfg = np.moveaxis(array,1,3).shape
print(gfg)

(1, 3, 4, 2)


In [91]:
# Interchange two axes of an array

arr = np.array([[2, 4, 6,5,7]])
result = np.swapaxes(arr,0,1)
print(result)

[[2]
 [4]
 [6]
 [5]
 [7]]


In [94]:
# Counts the number of non-zero values in the array

arr = [[0, 1, 2, 3, 0], [0, 5, 6, 0, 7],[11,5,9,0,0]]

# array = np.array(arr)
array = np.count_nonzero(arr)
print(array)


9
