In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [186]:
mydata = pd.read_csv("C:\\Users\\Admin\\Desktop\\weather.csv")
pd.options.display.max_rows = 9999
mydata

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0        8.0     24.3       0.0          3.4       6.3          NW   
1       14.0     26.9       3.6          4.4       9.7         ENE   
2       13.7     23.4       3.6          5.8       3.3          NW   
3       13.3     15.5      39.8          7.2       9.1          NW   
4        7.6     16.1       2.8          5.6      10.6         SSE   
5        6.2     16.9       0.0          5.8       8.2          SE   
6        6.1     18.2       0.2          4.2       8.4          SE   
7        8.3     17.0       0.0          5.6       4.6           E   
8        8.8     19.5       0.0          4.0       4.1           S   
9        8.4     22.8      16.2          5.4       7.7           E   
10       9.1     25.2       0.0          4.2      11.9           N   
11       8.5     27.3       0.2          7.2      12.5           E   
12      10.1     27.9       0.0          7.2      13.0         WNW   
13      12.1     30.9       0.0          6.2      12.4          NW   
14      10.1     31.2       0.0          8.8      13.1          NW   
15      12.4     32.1       0.0          8.4      11.1           E   
16      13.8     31.2       0.0          7.2       8.4         ESE   
17      11.7     30.0       1.2          7.2      10.1           S   
18      12.4     32.3       0.6          7.4      13.0           E   
19      15.6     33.4       0.0          8.0      10.4          NE   
20      15.3     33.4       0.0          8.8       9.5         WNW   
21      16.4     19.4       0.4          9.2       0.0           E   
22      12.8     18.5      25.8          2.8       0.6         ESE   
23      12.0     24.3       0.4          1.2       7.5         NNE   
24      15.4     28.4       0.0          4.4       8.1         ENE   
25      15.6     26.9       0.0          6.8       8.9           E   
26      13.3     22.2       0.2          6.6       2.3         ENE   
27      12.9     28.0       0.0          4.4      10.7           S   
28      15.1     24.3       0.0          7.0       0.4          SE   
29      13.6     24.1       0.4          2.6       0.5         NNW   
30      15.1     20.4      22.6          2.4       0.2         SSE   
31      11.6     26.3       4.2          1.6      12.0         NNE   
32      16.6     24.2       0.2          6.6       4.7          NW   
33      13.3     26.5       6.6          3.8      11.8          NW   
34      14.5     21.8       0.0          8.4       9.8         ENE   
35      16.3     26.8       0.0          6.0       6.3         ENE   
36      17.2     25.8       0.0          4.2       8.8          SW   
37      16.5     28.2       4.0          4.2       8.8          NE   
38      15.0     29.4       0.0          6.6      11.1          NW   
39      14.9     24.8       0.0         10.4      10.0         NNW   
40      11.8     18.5       0.6          4.8       2.3         ENE   
41      11.7     21.5       0.0          4.2       7.3         ENE   
42       9.6     20.3       0.0          5.0       3.6          SE   
43       8.9     27.1       0.0          4.4      12.7           E   
44      10.1     29.9       0.0          6.8       8.8           E   
45      15.5     21.1       5.4          6.4       0.9           S   
46      10.8     21.7       1.4          2.8      10.6         ESE   
47       7.5     20.9       0.0          6.6       8.7         ENE   
48      12.8     21.0       0.0          6.4       0.8          NE   
49      12.6     23.1       3.4          1.6       2.3         NNW   
50      14.8     29.5       6.4          1.8       8.1           N   
51      19.9     22.0      11.0          4.4       5.9         NNW   
52       9.2     20.4      17.4          7.8      10.2         ENE   
53      12.4     24.4       0.0          6.2      12.1          NW   
54      11.3     21.7       3.4          8.2       5.6           E   
55       9.8     26.3       0.0          5.2      13.0         NNW   
56      14.3   

In [8]:
values = np.linspace(0, 10, num=10)
print(values)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [10]:
result = np.arange(10)
result

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
result = np.arange(1,15,3)
result

array([ 1,  4,  7, 10, 13])

In [13]:
result = np.ones((2,2))
result

array([[1., 1.],
       [1., 1.]])

In [14]:
print(np.ones((2,2)))

[[1. 1.]
 [1. 1.]]


In [16]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [20]:
print(np.full((3,3),2))

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [25]:
c = np.eye(4,4) 
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
print(np.eye(3,2))

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [30]:
print(np.eye(5,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [33]:
print(np.diag([1,3,5,7,9])) # create matrix

[[1 0 0 0 0]
 [0 3 0 0 0]
 [0 0 5 0 0]
 [0 0 0 7 0]
 [0 0 0 0 9]]


In [35]:
original_matrix = np.diag([2,4,6,8,10])
modify_matrix = np.where(original_matrix == 0, "*", original_matrix)
print(modify_matrix)

[['2' '*' '*' '*' '*']
 ['*' '4' '*' '*' '*']
 ['*' '*' '6' '*' '*']
 ['*' '*' '*' '8' '*']
 ['*' '*' '*' '*' '10']]


In [32]:
original_matrix = np.diag([1, 2, 3, 4]) # modified matrix 
modified_matrix = np.where(original_matrix == 0, '*', original_matrix)
# replace o to * 

print(modified_matrix)


[['1' '*' '*' '*']
 ['*' '2' '*' '*']
 ['*' '*' '3' '*']
 ['*' '*' '*' '4']]


In [36]:
result = np.random.rand(3) # create a random number generate
print(result)

[0.44485749 0.77379345 0.45602628]


In [37]:
print(np.random.rand((4)))

[0.09814969 0.75710356 0.41152694 0.83849105]


In [40]:
print(np.random.randn((4)))

[-0.95985017  0.47629601  0.5528416  -0.28248584]


In [41]:
a = np.arange(1)
#print(np.arange(1))
print(type(a))

<class 'numpy.ndarray'>


In [44]:
result = np.arange(20)
result.dtype

dtype('int32')

In [45]:
result = np.arange(30)
result.dtype

dtype('int32')

In [46]:
result = np.arange(1.2)
result.dtype

dtype('float64')

In [48]:
result = np.arange(5, dtype = 'float64')
result

array([0., 1., 2., 3., 4.])

In [51]:
result = np.array([1+2j , 2+2j])
result.dtype

dtype('complex128')

In [52]:
d = np.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [56]:
result = np.array([True,False])
result.dtype

dtype('bool')

In [57]:
result = np.arange(10)
print(result[5])

5


In [70]:
a[2, 1] = 5 #assigning value

a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 5., 0.]])

In [71]:
a[2,1] = 5
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 5., 0.]])

In [73]:
a[2, 1] = 5 #assigning value

a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 5., 0.]])

In [74]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [76]:
print(np.arange(1,10,3))

[1 4 7]


In [79]:
a = np.arange(10)
a[4:] = 9
print(a)

[0 1 2 3 9 9 9 9 9 9]


In [96]:
a = np.arange(10)
a[4:] = [-1,-2,-3,-4,-5,-6]
print(a)

[ 0  1  2  3 -1 -2 -3 -4 -5 -6]


In [97]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [103]:
np.shares_memory(a,b)

True

In [107]:
b[1] = 5
b

array([0, 5, 4, 6, 8])

In [108]:
a

array([0, 1, 5, 3, 4, 5, 6, 7, 8, 9])

In [110]:
a = np.arange(10)
c = a[::1].copy()
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
np.shares_memory(a,b)

False

In [112]:
np.shares_memory(a,c)

False

In [113]:
c[1] = 2
c

array([0, 2, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
a = np.random.randint(0,20,15)
a

array([11,  6,  4,  3, 10,  9, 12,  2,  6,  8, 14, 18, 11, 18,  4])

In [119]:
b = a % 2 == 0
b

array([False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True])

In [120]:
a[b]

array([ 6,  4, 10, 12,  2,  6,  8, 14, 18, 18,  4])

In [121]:
a = np.arange(150)
a


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149])

In [122]:
a = np.arange(0,150,10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140])

In [123]:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [124]:
a[[1,5,9,1,2]]

array([10, 50, 90, 10, 20])

In [126]:
a[[5,2]] = 900
a

array([  0,  10, 900,  30,  40, 900,  60,  70,  80,  90, 100, 110, 120,
       130, 140])

In [127]:
from numpy import random

# 	Arithmetic Array Operations

In [140]:
a = np.array([5,20,50,35])
b = np.array([4,60,80,90])

add = a+b
print("addition :" , add)
sub = a-b
print("substact :" , sub)

mul = a*b
print("multiplication :" , mul)
div = a/b
print("division :" , div)

addition : [  9  80 130 125]
substact : [  1 -40 -30 -55]
multiplication : [  20 1200 4000 3150]
division : [1.25       0.33333333 0.625      0.38888889]


In [142]:
a = np.array([2,4,6])
result = a ** 2
result

array([ 4, 16, 36], dtype=int32)

In [144]:
a = np.array([1,2,3,4])
result = -a
result

array([-1, -2, -3, -4])

# 	Constants

In [145]:
pi_value = np.pi
pi_value

3.141592653589793

In [146]:
e_value = np.e
e_value

2.718281828459045

# 	Statistical Functions

In [153]:
mydata = np.array([10,20,30,40,50,25,60,35,60,85])
mean_value = np.mean(mydata)
print("mean : " ,mean_value)

mean :  41.5


In [154]:
median_value = np.median(mydata)
median_value

37.5

In [155]:
std_dv_value = np.std(mydata)
std_dv_value

21.33658829335187

In [156]:
variance = np.var(mydata)
variance

455.25

In [157]:
min_value = np.min(mydata)
min_value

10

In [158]:
max_value = np.max(mydata)
max_value

85

In [159]:
sum_value = np.sum(mydata)
sum_value

415

# 	String Functions

In [164]:
a = np.array(["hello"])
b = np.array(["python"])
str_concate = np.char.add(a, b)
str_concate

array(['hellopython'], dtype='<U11')

In [173]:
a = np.array(["Hello", "python"]) # string concate
b = np.array([" ", " !"])
print(np.char.add(a,b))

['Hello ' 'python !']


In [177]:
print(np.char.multiply(a , 2)) # string multiply

['HelloHello' 'pythonpython']


In [180]:
print(np.char.str_len(a)) # string find lengh

[5 6]


In [181]:
a = np.array(["apple","banana","cherry"])
b = np.array(["watermelon", "banana","apple"])

result = np.char.not_equal(a,b)
result

array([ True, False,  True])

In [182]:
a = np.array(["apple","banana","cherry"])
b = np.array(["watermelon", "banana","apple"])

result = np.char.equal(a,b)
result

array([False,  True, False])

In [184]:
a = np.array(["Hello", "Python", "World"])

result = np.char.lower(a)
print(result)

result1 = np.char.upper(a)
print(result1)

['hello' 'python' 'world']
['HELLO' 'PYTHON' 'WORLD']


In [187]:
mydata = pd.read_csv("employee data.csv")
mydata

SR NO    EEID             Full Name                       Job Title  \
0       1  E04125           Emily Davis                      Sr. Manger   
1       2  E04105         Theodore Dinh             Technical Architect   
2       3  E02572          Luna Sanders                        Director   
3       4  E02832       Penelope Jordan        Computer Systems Manager   
4       5  E01639             Austin Vo                     Sr. Analyst   
5       6  E00644          Joshua Gupta          Account Representative   
6       7  E01550           Ruby Barnes                         Manager   
7       8  E04332           Luke Martin                         Analyst   
8       9  E04533         Easton Bailey                         Manager   
9      10  E03838       Madeline Walker                     Sr. Analyst   
10     11  E00591          Savannah Ali                      Sr. Manger   
11     12  E03344         Camila Rogers               Controls Engineer   
12     13  E00530             Eli Jones                         Manager   
13     14  E04239          Everleigh Ng                      Sr. Manger   
14     15  E03496           Robert Yang                     Sr. Analyst   
15     16  E00549           Isabella Xi                  Vice President   
16     17  E00163          Bella Powell                        Director   
17     18  E00884          Camila Silva                      Sr. Manger   
18     19  E04116          David Barnes                        Director   
19     20  E04625             Adam Dang                        Director   
20     21  E03680        Elias Alvarado                      Sr. Manger   
21     22  E04732            Eva Rivera                        Director   
22     23  E03484          Logan Rivera                        Director   
23     24  E00671        Leonardo Dixon                         Analyst   
24     25  E02071             Mateo Her                  Vice President   
25     26  E02206        Jose Henderson                        Director   
26     27  E04545         Abigail Mejia                Quality Engineer   
27     28  E00154            Wyatt Chin                  Vice President   
28     29  E03343             Carson Lu             Engineering Manager   
29     30  E00304            Dylan Choi                  Vice President   
30     31  E02594         Ezekiel Kumar                  IT Coordinator   
31     32  E00402        Dominic Guzman                         Analyst   
32     33  E01994          Angel Powell                      Analyst II   
33     34  E03549              Mateo Vu          Account Representative   
34     35  E03247      Caroline Jenkins                         Analyst   
35     36  E02074            Nora Brown            Enterprise Architect   
36     37  E04152         Adeline Huang               Controls Engineer   
37     38  E01628         Jackson Perry                  Vice President   
38     39  E04285         Riley Padilla             Technical Architect   
39     40  E01417             Leah Pena            Enterprise Architect   
40     41  E01754              Owen Lam            Sr. Business Partner   
41     42  E03749        Kennedy Foster                         Manager   
42     43  E03574            John Moore                  Vice President   
43     44  E04600            William Vu          Account Representative   
44     45  E00586      Sadie Washington                      Sr. Manger   
45     46  E03538        Gabriel Holmes            Enterprise Architect   
46     47  E02185           Wyatt Rojas        Computer Systems Manager   
47     48  E03830           Eva Coleman                        Director   
48     49  E03720         Dominic Clark                Quality Engineer   
49     50  E03025        Lucy Alexander                        Director   
50     51  E04917  Everleigh Washington                    HRIS Analyst   
51     52  E00415        Leilani Butler                      Analyst II   
52     53  E02862          Pe

In [189]:
print(mydata.head(10))


   SR NO    EEID        Full Name                 Job Title  Department  \
0      1  E04125      Emily Davis                Sr. Manger          IT   
1      2  E04105    Theodore Dinh       Technical Architect          IT   
2      3  E02572     Luna Sanders                  Director     Finance   
3      4  E02832  Penelope Jordan  Computer Systems Manager          IT   
4      5  E01639        Austin Vo               Sr. Analyst     Finance   
5      6  E00644     Joshua Gupta    Account Representative       Sales   
6      7  E01550      Ruby Barnes                   Manager          IT   
7      8  E04332      Luke Martin                   Analyst     Finance   
8      9  E04533    Easton Bailey                   Manager  Accounting   
9     10  E03838  Madeline Walker               Sr. Analyst     Finance   

   Gender  Age   Hire Date Annual Salary Bonus %       City   Exit Date  
0  Female   55  04/08/2016     $141,604      15%    Seattle  10/16/2021  
1    Male   59  11/29/1997

In [190]:
print(mydata.head())

   SR NO    EEID        Full Name                 Job Title Department  \
0      1  E04125      Emily Davis                Sr. Manger         IT   
1      2  E04105    Theodore Dinh       Technical Architect         IT   
2      3  E02572     Luna Sanders                  Director    Finance   
3      4  E02832  Penelope Jordan  Computer Systems Manager         IT   
4      5  E01639        Austin Vo               Sr. Analyst    Finance   

   Gender  Age   Hire Date Annual Salary Bonus %       City   Exit Date  
0  Female   55  04/08/2016     $141,604      15%    Seattle  10/16/2021  
1    Male   59  11/29/1997      $99,975       0%  Chongqing         NaN  
2  Female   50  10/26/2006     $163,099      20%    Chicago         NaN  
3  Female   26   9/27/2019      $84,913       7%    Chicago         NaN  
4    Male   55  11/20/1995      $95,409       0%    Phoenix         NaN  


In [191]:
print(mydata.tail())

    SR NO    EEID     Full Name                 Job Title Department  Gender  \
95     96  E01427     Mia Cheng                Sr. Manger      Sales  Female   
96     97  E04568      Rylee Yu            Vice President    Finance  Female   
97     98  E04931    Zoe Romero         Network Architect         IT  Female   
98     99  E00443     Nolan Bui  Computer Systems Manager         IT    Male   
99    100  E03890  Nevaeh Jones            Vice President      Sales  Female   

    Age   Hire Date Annual Salary Bonus %       City Exit Date  
95   34   4/22/2015     $154,941      13%    Phoenix       NaN  
96   54  07/10/2011     $247,022      30%    Beijing       NaN  
97   32  10/05/2021      $88,072       0%  Sao Paulo       NaN  
98   28   5/26/2020      $67,925       8%   Shanghai       NaN  
99   31   8/20/2020     $219,693      30%     Austin       NaN  


In [192]:
print(mydata.tail(10))

    SR NO    EEID       Full Name                 Job Title       Department  \
90     91  E00440      Jack Huynh                   Manager        Marketing   
91     92  E00595     Everly Chow                Sr. Manger          Finance   
92     93  E00972  Amelia Salazar                Analyst II          Finance   
93     94  E04562    Xavier Zheng    Account Representative            Sales   
94     95  E02802    Matthew Chau      Sr. Business Partner  Human Resources   
95     96  E01427       Mia Cheng                Sr. Manger            Sales   
96     97  E04568        Rylee Yu            Vice President          Finance   
97     98  E04931      Zoe Romero         Network Architect               IT   
98     99  E00443       Nolan Bui  Computer Systems Manager               IT   
99    100  E03890    Nevaeh Jones            Vice President            Sales   

    Gender  Age   Hire Date Annual Salary Bonus %       City   Exit Date  
90    Male   27   9/25/2018     $114,441    

In [194]:
print(mydata.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   SR NO          100 non-null    int64 
 1   EEID           100 non-null    object
 2   Full Name      100 non-null    object
 3   Job Title      100 non-null    object
 4   Department     100 non-null    object
 5   Gender         100 non-null    object
 6   Age            100 non-null    int64 
 7   Hire Date      100 non-null    object
 8   Annual Salary  100 non-null    object
 9   Bonus %        100 non-null    object
 10  City           100 non-null    object
 11  Exit Date      12 non-null     object
dtypes: int64(2), object(10)
memory usage: 9.5+ KB
None


In [195]:
print(mydata.dropna())

    SR NO    EEID            Full Name             Job Title       Department  \
0       1  E04125          Emily Davis            Sr. Manger               IT   
7       8  E04332          Luke Martin               Analyst          Finance   
14     15  E03496          Robert Yang           Sr. Analyst       Accounting   
40     41  E01754             Owen Lam  Sr. Business Partner  Human Resources   
61     62  E00502      Natalia Salazar           Sr. Analyst       Accounting   
62     63  E04000      Skylar Carrillo   Engineering Manager      Engineering   
66     67  E00436        Everly Walker          HRIS Analyst  Human Resources   
70     71  E02966       William Foster        Field Engineer      Engineering   
75     76  E01540        Miles Salazar        IT Coordinator               IT   
76     77  E04474            Mila Hong         Test Engineer      Engineering   
83     84  E00416  Everleigh Fernandez              Director      Engineering   
90     91  E00440           

In [215]:
mydata.dropna(inplace = True)
mydata

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0        8.0     24.3       0.0          3.4       6.3          NW   
1       14.0     26.9       3.6          4.4       9.7         ENE   
2       13.7     23.4       3.6          5.8       3.3          NW   
3       13.3     15.5      39.8          7.2       9.1          NW   
4        7.6     16.1       2.8          5.6      10.6         SSE   
5        6.2     16.9       0.0          5.8       8.2          SE   
6        6.1     18.2       0.2          4.2       8.4          SE   
7        8.3     17.0       0.0          5.6       4.6           E   
8        8.8     19.5       0.0          4.0       4.1           S   
9        8.4     22.8      16.2          5.4       7.7           E   
10       9.1     25.2       0.0          4.2      11.9           N   
11       8.5     27.3       0.2          7.2      12.5           E   
12      10.1     27.9       0.0          7.2      13.0         WNW   
13      12.1     30.9       0.0          6.2      12.4          NW   
14      10.1     31.2       0.0          8.8      13.1          NW   
15      12.4     32.1       0.0          8.4      11.1           E   
16      13.8     31.2       0.0          7.2       8.4         ESE   
17      11.7     30.0       1.2          7.2      10.1           S   
18      12.4     32.3       0.6          7.4      13.0           E   
19      15.6     33.4       0.0          8.0      10.4          NE   
20      15.3     33.4       0.0          8.8       9.5         WNW   
21      16.4     19.4       0.4          9.2       0.0           E   
22      12.8     18.5      25.8          2.8       0.6         ESE   
23      12.0     24.3       0.4          1.2       7.5         NNE   
24      15.4     28.4       0.0          4.4       8.1         ENE   
25      15.6     26.9       0.0          6.8       8.9           E   
26      13.3     22.2       0.2          6.6       2.3         ENE   
27      12.9     28.0       0.0          4.4      10.7           S   
28      15.1     24.3       0.0          7.0       0.4          SE   
29      13.6     24.1       0.4          2.6       0.5         NNW   
30      15.1     20.4      22.6          2.4       0.2         SSE   
31      11.6     26.3       4.2          1.6      12.0         NNE   
32      16.6     24.2       0.2          6.6       4.7          NW   
33      13.3     26.5       6.6          3.8      11.8          NW   
34      14.5     21.8       0.0          8.4       9.8         ENE   
35      16.3     26.8       0.0          6.0       6.3         ENE   
36      17.2     25.8       0.0          4.2       8.8          SW   
37      16.5     28.2       4.0          4.2       8.8          NE   
38      15.0     29.4       0.0          6.6      11.1          NW   
39      14.9     24.8       0.0         10.4      10.0         NNW   
40      11.8     18.5       0.6          4.8       2.3         ENE   
41      11.7     21.5       0.0          4.2       7.3         ENE   
42       9.6     20.3       0.0          5.0       3.6          SE   
43       8.9     27.1       0.0          4.4      12.7           E   
44      10.1     29.9       0.0          6.8       8.8           E   
45      15.5     21.1       5.4          6.4       0.9           S   
46      10.8     21.7       1.4          2.8      10.6         ESE   
47       7.5     20.9       0.0          6.6       8.7         ENE   
48      12.8     21.0       0.0          6.4       0.8          NE   
49      12.6     23.1       3.4          1.6       2.3         NNW   
50      14.8     29.5       6.4          1.8       8.1           N   
51      19.9     22.0      11.0          4.4       5.9         NNW   
52       9.2     20.4      17.4          7.8      10.2         ENE   
53      12.4     24.4       0.0          6.2      12.1          NW   
54      11.3     21.7       3.4          8.2       5.6           E   
55       9.8     26.3       0.0          5.2      13.0         NNW   
56      14.3   

In [202]:
mydata = pd.read_csv("weather.csv") # load data to csv file
mydata

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0        8.0     24.3       0.0          3.4       6.3          NW   
1       14.0     26.9       3.6          4.4       9.7         ENE   
2       13.7     23.4       3.6          5.8       3.3          NW   
3       13.3     15.5      39.8          7.2       9.1          NW   
4        7.6     16.1       2.8          5.6      10.6         SSE   
5        6.2     16.9       0.0          5.8       8.2          SE   
6        6.1     18.2       0.2          4.2       8.4          SE   
7        8.3     17.0       0.0          5.6       4.6           E   
8        8.8     19.5       0.0          4.0       4.1           S   
9        8.4     22.8      16.2          5.4       7.7           E   
10       9.1     25.2       0.0          4.2      11.9           N   
11       8.5     27.3       0.2          7.2      12.5           E   
12      10.1     27.9       0.0          7.2      13.0         WNW   
13      12.1     30.9       0.0          6.2      12.4          NW   
14      10.1     31.2       0.0          8.8      13.1          NW   
15      12.4     32.1       0.0          8.4      11.1           E   
16      13.8     31.2       0.0          7.2       8.4         ESE   
17      11.7     30.0       1.2          7.2      10.1           S   
18      12.4     32.3       0.6          7.4      13.0           E   
19      15.6     33.4       0.0          8.0      10.4          NE   
20      15.3     33.4       0.0          8.8       9.5         WNW   
21      16.4     19.4       0.4          9.2       0.0           E   
22      12.8     18.5      25.8          2.8       0.6         ESE   
23      12.0     24.3       0.4          1.2       7.5         NNE   
24      15.4     28.4       0.0          4.4       8.1         ENE   
25      15.6     26.9       0.0          6.8       8.9           E   
26      13.3     22.2       0.2          6.6       2.3         ENE   
27      12.9     28.0       0.0          4.4      10.7           S   
28      15.1     24.3       0.0          7.0       0.4          SE   
29      13.6     24.1       0.4          2.6       0.5         NNW   
30      15.1     20.4      22.6          2.4       0.2         SSE   
31      11.6     26.3       4.2          1.6      12.0         NNE   
32      16.6     24.2       0.2          6.6       4.7          NW   
33      13.3     26.5       6.6          3.8      11.8          NW   
34      14.5     21.8       0.0          8.4       9.8         ENE   
35      16.3     26.8       0.0          6.0       6.3         ENE   
36      17.2     25.8       0.0          4.2       8.8          SW   
37      16.5     28.2       4.0          4.2       8.8          NE   
38      15.0     29.4       0.0          6.6      11.1          NW   
39      14.9     24.8       0.0         10.4      10.0         NNW   
40      11.8     18.5       0.6          4.8       2.3         ENE   
41      11.7     21.5       0.0          4.2       7.3         ENE   
42       9.6     20.3       0.0          5.0       3.6          SE   
43       8.9     27.1       0.0          4.4      12.7           E   
44      10.1     29.9       0.0          6.8       8.8           E   
45      15.5     21.1       5.4          6.4       0.9           S   
46      10.8     21.7       1.4          2.8      10.6         ESE   
47       7.5     20.9       0.0          6.6       8.7         ENE   
48      12.8     21.0       0.0          6.4       0.8          NE   
49      12.6     23.1       3.4          1.6       2.3         NNW   
50      14.8     29.5       6.4          1.8       8.1           N   
51      19.9     22.0      11.0          4.4       5.9         NNW   
52       9.2     20.4      17.4          7.8      10.2         ENE   
53      12.4     24.4       0.0          6.2      12.1          NW   
54      11.3     21.7       3.4          8.2       5.6           E   
55       9.8     26.3       0.0          5.2      13.0         NNW   
56      14.3   

In [203]:
print(mydata.head()) # Heading data to show total 5 row show

   MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0      8.0     24.3       0.0          3.4       6.3          NW   
1     14.0     26.9       3.6          4.4       9.7         ENE   
2     13.7     23.4       3.6          5.8       3.3          NW   
3     13.3     15.5      39.8          7.2       9.1          NW   
4      7.6     16.1       2.8          5.6      10.6         SSE   

   WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
0           30.0         SW         NW           6.0  ...           29   
1           39.0          E          W           4.0  ...           36   
2           85.0          N        NNE           6.0  ...           69   
3           54.0        WNW          W          30.0  ...           56   
4           50.0        SSE        ESE          20.0  ...           49   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1019.7       1015.0         7         7     14.4     23.6 

In [204]:
print(mydata.tail()) # last 5 row show

     MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
361      9.0     30.7       0.0          7.6      12.1         NNW   
362      7.1     28.4       0.0         11.6      12.7           N   
363     12.5     19.9       0.0          8.4       5.3         ESE   
364     12.5     26.9       0.0          5.0       7.1          NW   
365     12.3     30.2       0.0          6.0      12.6          NW   

     WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
361           76.0        SSE         NW           7.0  ...           15   
362           48.0        NNW        NNW           2.0  ...           22   
363           43.0        ENE        ENE          11.0  ...           47   
364           46.0        SSW        WNW           6.0  ...           39   
365           78.0         NW        WNW          31.0  ...           13   

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
361       1016.1       1010.8         1         3  

In [205]:
print(mydata.head(10)) # first 5 row show in csv file

   MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0      8.0     24.3       0.0          3.4       6.3          NW   
1     14.0     26.9       3.6          4.4       9.7         ENE   
2     13.7     23.4       3.6          5.8       3.3          NW   
3     13.3     15.5      39.8          7.2       9.1          NW   
4      7.6     16.1       2.8          5.6      10.6         SSE   
5      6.2     16.9       0.0          5.8       8.2          SE   
6      6.1     18.2       0.2          4.2       8.4          SE   
7      8.3     17.0       0.0          5.6       4.6           E   
8      8.8     19.5       0.0          4.0       4.1           S   
9      8.4     22.8      16.2          5.4       7.7           E   

   WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
0           30.0         SW         NW           6.0  ...           29   
1           39.0          E          W           4.0  ...           36   
2           85.0          N  

In [206]:
print(mydata.tail(10)) # last 10 row show in csv file

     MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
356      3.4     15.0       0.8          4.8      11.7           S   
357      3.2     18.0       0.0          7.4      12.2         SSE   
358      0.9     20.7       0.0          5.4       8.4         NNW   
359      3.3     25.5       0.0          5.2      10.8           N   
360      7.9     26.1       0.0          6.8       3.5         NNW   
361      9.0     30.7       0.0          7.6      12.1         NNW   
362      7.1     28.4       0.0         11.6      12.7           N   
363     12.5     19.9       0.0          8.4       5.3         ESE   
364     12.5     26.9       0.0          5.0       7.1          NW   
365     12.3     30.2       0.0          6.0      12.6          NW   

     WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
356           70.0          S          S          35.0  ...           24   
357           48.0        SSE          S          26.0  ...           25   
3

In [211]:
mydata1 = mydata.dropna()
#print(mydata1.to_string())
mydata1

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0        8.0     24.3       0.0          3.4       6.3          NW   
1       14.0     26.9       3.6          4.4       9.7         ENE   
2       13.7     23.4       3.6          5.8       3.3          NW   
3       13.3     15.5      39.8          7.2       9.1          NW   
4        7.6     16.1       2.8          5.6      10.6         SSE   
5        6.2     16.9       0.0          5.8       8.2          SE   
6        6.1     18.2       0.2          4.2       8.4          SE   
7        8.3     17.0       0.0          5.6       4.6           E   
8        8.8     19.5       0.0          4.0       4.1           S   
9        8.4     22.8      16.2          5.4       7.7           E   
10       9.1     25.2       0.0          4.2      11.9           N   
11       8.5     27.3       0.2          7.2      12.5           E   
12      10.1     27.9       0.0          7.2      13.0         WNW   
13      12.1     30.9       0.0          6.2      12.4          NW   
14      10.1     31.2       0.0          8.8      13.1          NW   
15      12.4     32.1       0.0          8.4      11.1           E   
16      13.8     31.2       0.0          7.2       8.4         ESE   
17      11.7     30.0       1.2          7.2      10.1           S   
18      12.4     32.3       0.6          7.4      13.0           E   
19      15.6     33.4       0.0          8.0      10.4          NE   
20      15.3     33.4       0.0          8.8       9.5         WNW   
21      16.4     19.4       0.4          9.2       0.0           E   
22      12.8     18.5      25.8          2.8       0.6         ESE   
23      12.0     24.3       0.4          1.2       7.5         NNE   
24      15.4     28.4       0.0          4.4       8.1         ENE   
25      15.6     26.9       0.0          6.8       8.9           E   
26      13.3     22.2       0.2          6.6       2.3         ENE   
27      12.9     28.0       0.0          4.4      10.7           S   
28      15.1     24.3       0.0          7.0       0.4          SE   
29      13.6     24.1       0.4          2.6       0.5         NNW   
30      15.1     20.4      22.6          2.4       0.2         SSE   
31      11.6     26.3       4.2          1.6      12.0         NNE   
32      16.6     24.2       0.2          6.6       4.7          NW   
33      13.3     26.5       6.6          3.8      11.8          NW   
34      14.5     21.8       0.0          8.4       9.8         ENE   
35      16.3     26.8       0.0          6.0       6.3         ENE   
36      17.2     25.8       0.0          4.2       8.8          SW   
37      16.5     28.2       4.0          4.2       8.8          NE   
38      15.0     29.4       0.0          6.6      11.1          NW   
39      14.9     24.8       0.0         10.4      10.0         NNW   
40      11.8     18.5       0.6          4.8       2.3         ENE   
41      11.7     21.5       0.0          4.2       7.3         ENE   
42       9.6     20.3       0.0          5.0       3.6          SE   
43       8.9     27.1       0.0          4.4      12.7           E   
44      10.1     29.9       0.0          6.8       8.8           E   
45      15.5     21.1       5.4          6.4       0.9           S   
46      10.8     21.7       1.4          2.8      10.6         ESE   
47       7.5     20.9       0.0          6.6       8.7         ENE   
48      12.8     21.0       0.0          6.4       0.8          NE   
49      12.6     23.1       3.4          1.6       2.3         NNW   
50      14.8     29.5       6.4          1.8       8.1           N   
51      19.9     22.0      11.0          4.4       5.9         NNW   
52       9.2     20.4      17.4          7.8      10.2         ENE   
53      12.4     24.4       0.0          6.2      12.1          NW   
54      11.3     21.7       3.4          8.2       5.6           E   
55       9.8     26.3       0.0          5.2      13.0         NNW   
56      14.3   

In [209]:
mydata1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 328 entries, 0 to 365
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   MinTemp        328 non-null    float64
 1   MaxTemp        328 non-null    float64
 2   Rainfall       328 non-null    float64
 3   Evaporation    328 non-null    float64
 4   Sunshine       328 non-null    float64
 5   WindGustDir    328 non-null    object 
 6   WindGustSpeed  328 non-null    float64
 7   WindDir9am     328 non-null    object 
 8   WindDir3pm     328 non-null    object 
 9   WindSpeed9am   328 non-null    float64
 10  WindSpeed3pm   328 non-null    int64  
 11  Humidity9am    328 non-null    int64  
 12  Humidity3pm    328 non-null    int64  
 13  Pressure9am    328 non-null    float64
 14  Pressure3pm    328 non-null    float64
 15  Cloud9am       328 non-null    int64  
 16  Cloud3pm       328 non-null    int64  
 17  Temp9am        328 non-null    float64
 18  Temp3pm   

In [213]:
mydata.dropna(inplace=True)
mydata

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0        8.0     24.3       0.0          3.4       6.3          NW   
1       14.0     26.9       3.6          4.4       9.7         ENE   
2       13.7     23.4       3.6          5.8       3.3          NW   
3       13.3     15.5      39.8          7.2       9.1          NW   
4        7.6     16.1       2.8          5.6      10.6         SSE   
5        6.2     16.9       0.0          5.8       8.2          SE   
6        6.1     18.2       0.2          4.2       8.4          SE   
7        8.3     17.0       0.0          5.6       4.6           E   
8        8.8     19.5       0.0          4.0       4.1           S   
9        8.4     22.8      16.2          5.4       7.7           E   
10       9.1     25.2       0.0          4.2      11.9           N   
11       8.5     27.3       0.2          7.2      12.5           E   
12      10.1     27.9       0.0          7.2      13.0         WNW   
13      12.1     30.9       0.0          6.2      12.4          NW   
14      10.1     31.2       0.0          8.8      13.1          NW   
15      12.4     32.1       0.0          8.4      11.1           E   
16      13.8     31.2       0.0          7.2       8.4         ESE   
17      11.7     30.0       1.2          7.2      10.1           S   
18      12.4     32.3       0.6          7.4      13.0           E   
19      15.6     33.4       0.0          8.0      10.4          NE   
20      15.3     33.4       0.0          8.8       9.5         WNW   
21      16.4     19.4       0.4          9.2       0.0           E   
22      12.8     18.5      25.8          2.8       0.6         ESE   
23      12.0     24.3       0.4          1.2       7.5         NNE   
24      15.4     28.4       0.0          4.4       8.1         ENE   
25      15.6     26.9       0.0          6.8       8.9           E   
26      13.3     22.2       0.2          6.6       2.3         ENE   
27      12.9     28.0       0.0          4.4      10.7           S   
28      15.1     24.3       0.0          7.0       0.4          SE   
29      13.6     24.1       0.4          2.6       0.5         NNW   
30      15.1     20.4      22.6          2.4       0.2         SSE   
31      11.6     26.3       4.2          1.6      12.0         NNE   
32      16.6     24.2       0.2          6.6       4.7          NW   
33      13.3     26.5       6.6          3.8      11.8          NW   
34      14.5     21.8       0.0          8.4       9.8         ENE   
35      16.3     26.8       0.0          6.0       6.3         ENE   
36      17.2     25.8       0.0          4.2       8.8          SW   
37      16.5     28.2       4.0          4.2       8.8          NE   
38      15.0     29.4       0.0          6.6      11.1          NW   
39      14.9     24.8       0.0         10.4      10.0         NNW   
40      11.8     18.5       0.6          4.8       2.3         ENE   
41      11.7     21.5       0.0          4.2       7.3         ENE   
42       9.6     20.3       0.0          5.0       3.6          SE   
43       8.9     27.1       0.0          4.4      12.7           E   
44      10.1     29.9       0.0          6.8       8.8           E   
45      15.5     21.1       5.4          6.4       0.9           S   
46      10.8     21.7       1.4          2.8      10.6         ESE   
47       7.5     20.9       0.0          6.6       8.7         ENE   
48      12.8     21.0       0.0          6.4       0.8          NE   
49      12.6     23.1       3.4          1.6       2.3         NNW   
50      14.8     29.5       6.4          1.8       8.1           N   
51      19.9     22.0      11.0          4.4       5.9         NNW   
52       9.2     20.4      17.4          7.8      10.2         ENE   
53      12.4     24.4       0.0          6.2      12.1          NW   
54      11.3     21.7       3.4          8.2       5.6           E   
55       9.8     26.3       0.0          5.2      13.0         NNW   
56      14.3   

In [216]:
data1 = pd.read_csv("data.csv")
data1

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       1

In [218]:
data2 = pd.read_csv("C:\\Users\\Admin\\Desktop\\data.csv")
data2

Duration  Pulse  Maxpulse  Calories
0        60.0  110.0     130.0     409.1
1        60.0  117.0     145.0     479.0
2        60.0  103.0     135.0     340.0
3        45.0  109.0     175.0     282.4
4        45.0  117.0     148.0     406.0
5        60.0  102.0     127.0     300.0
6        60.0  110.0     136.0     374.0
7        45.0  104.0     134.0     253.3
8        30.0  109.0     133.0     195.1
9        60.0   98.0     124.0     269.0
10       60.0  103.0     147.0     329.3
11       60.0  100.0     120.0     250.7
12       60.0  106.0     128.0     345.3
13       60.0  104.0     132.0     379.3
14       60.0   98.0     123.0     275.0
15       60.0   98.0     120.0     215.2
16       60.0  100.0     120.0     300.0
17       45.0   90.0     112.0       NaN
18       60.0  103.0     123.0     323.0
19       45.0   97.0     125.0     243.0
20       60.0  108.0     131.0     364.2
21       45.0  100.0     119.0     282.0
22       60.0  130.0     101.0     300.0
23       45.0  105.0     132.0     246.0
24       60.0  102.0     126.0     334.5
25       60.0  100.0     120.0     250.0
26       60.0   92.0     118.0     241.0
27       60.0  103.0     132.0       NaN
28       60.0  100.0     132.0     280.0
29       60.0  102.0     129.0     380.3
30       60.0   92.0     115.0     243.0
31       45.0   90.0     112.0     180.1
32       60.0  101.0     124.0     299.0
33       60.0   93.0     113.0     223.0
34       60.0  107.0     136.0     361.0
35       60.0  114.0     140.0     415.0
36       60.0  102.0     127.0     300.0
37       60.0  100.0     120.0     300.0
38       60.0  100.0     120.0     300.0
39       45.0  104.0     129.0     266.0
40       45.0   90.0     112.0     180.1
41       60.0   98.0     126.0     286.0
42       60.0  100.0     122.0     329.4
43       60.0  111.0     138.0     400.0
44       60.0  111.0     131.0     397.0
45       60.0   99.0     119.0     273.0
46       60.0  109.0     153.0     387.6
47       45.0  111.0     136.0     300.0
48       45.0  108.0     129.0     298.0
49       60.0  111.0     139.0     397.6
50       60.0  107.0     136.0     380.2
51       80.0  123.0     146.0     643.1
52       60.0  106.0     130.0     263.0
53       60.0  118.0       NaN     486.0
54       30.0  136.0     175.0     238.0
55       60.0  121.0     146.0     450.7
56       60.0    NaN     121.0     413.0
57       45.0  115.0     144.0     305.0
58       20.0  153.0     172.0     226.4
59       45.0  123.0     152.0     321.0
60      210.0  108.0       NaN    1376.0
61      160.0  110.0     137.0    1034.4
62      160.0  109.0     135.0     853.0
63       45.0  118.0     141.0     341.0
64       20.0  110.0     130.0     131.4
65      180.0   90.0     130.0     800.4
66      150.0    NaN     135.0     873.4
67      150.0  107.0     130.0     816.0
68       20.0  106.0     136.0     110.4
69      300.0  108.0     143.0    1500.2
70      150.0   97.0     129.0    1115.0
71       60.0    NaN     153.0     387.6
72       90.0  100.0     127.0     700.0
73      150.0   97.0     127.0     953.2
74       45.0  114.0     146.0     304.0
75       90.0   98.0     125.0     563.2
76       45.0  105.0     134.0     251.0
77       45.0  110.0     141.0     300.0
78      120.0  100.0     130.0     500.4
79      270.0  100.0     131.0    1729.0
80       30.0  159.0     182.0     319.2
81       45.0  149.0     169.0     344.0
82       30.0  103.0     139.0     151.1
83      120.0  100.0     130.0     500.0
84       45.0    NaN     120.0     225.3
85       30.0  151.0     170.0     300.0
86       45.0  102.0     136.0     234.0
87      120.0  100.0     157.0    1000.1
88       45.0  129.0     103.0     242.0
89       20.0   83.0     107.0      50.3
90      180.0  101.0     127.0     600.1
91       45.0  107.0       NaN       NaN
92       30.0   90.0     107.0     105.3
93       15.0   80.0     100.0      50.5
94       20.0  150.0       NaN     127.4
95       20.0  151.0     168.0     229.4
96       30.0   95.0     128

In [221]:
print(data2.dropna())

     Duration  Pulse  Maxpulse  Calories
0        60.0  110.0     130.0     409.1
1        60.0  117.0     145.0     479.0
2        60.0  103.0     135.0     340.0
3        45.0  109.0     175.0     282.4
4        45.0  117.0     148.0     406.0
5        60.0  102.0     127.0     300.0
6        60.0  110.0     136.0     374.0
7        45.0  104.0     134.0     253.3
8        30.0  109.0     133.0     195.1
9        60.0   98.0     124.0     269.0
10       60.0  103.0     147.0     329.3
11       60.0  100.0     120.0     250.7
12       60.0  106.0     128.0     345.3
13       60.0  104.0     132.0     379.3
14       60.0   98.0     123.0     275.0
15       60.0   98.0     120.0     215.2
16       60.0  100.0     120.0     300.0
18       60.0  103.0     123.0     323.0
19       45.0   97.0     125.0     243.0
20       60.0  108.0     131.0     364.2
21       45.0  100.0     119.0     282.0
22       60.0  130.0     101.0     300.0
23       45.0  105.0     132.0     246.0
24       60.0  1

In [236]:
data_load = pd.read_csv("C:\\Users\\Admin\\Desktop\\data.csv")
data_load

Duration  Pulse  Maxpulse  Calories
0        60.0    NaN     130.0     409.1
1        60.0  117.0       NaN       NaN
2        60.0  103.0     135.0     340.0
3        45.0  109.0     175.0     282.4
4        45.0    NaN     148.0     406.0
5        60.0  102.0     127.0     300.0
6        60.0  110.0     136.0     374.0
7        45.0  104.0     134.0     253.3
8        30.0  109.0     133.0     195.1
9        60.0   98.0     124.0     269.0
10       60.0  103.0     147.0     329.3
11       60.0  100.0     120.0     250.7
12       60.0  106.0     128.0     345.3
13       60.0  104.0     132.0     379.3
14       60.0   98.0     123.0     275.0
15       60.0   98.0     120.0     215.2
16       60.0  100.0     120.0     300.0
17       45.0   90.0     112.0       NaN
18       60.0  103.0     123.0     323.0
19       45.0   97.0     125.0     243.0
20       60.0  108.0     131.0     364.2
21       45.0  100.0     119.0     282.0
22       60.0  130.0     101.0     300.0
23       45.0  105.0     132.0     246.0
24       60.0  102.0     126.0     334.5
25       60.0  100.0     120.0     250.0
26       60.0   92.0     118.0     241.0
27       60.0  103.0     132.0       NaN
28       60.0  100.0     132.0     280.0
29       60.0  102.0     129.0     380.3
30       60.0   92.0     115.0     243.0
31       45.0   90.0     112.0     180.1
32       60.0  101.0     124.0     299.0
33       60.0   93.0     113.0     223.0
34       60.0  107.0     136.0     361.0
35       60.0  114.0     140.0     415.0
36       60.0  102.0     127.0     300.0
37       60.0  100.0     120.0     300.0
38       60.0  100.0     120.0     300.0
39       45.0  104.0     129.0     266.0
40       45.0   90.0     112.0     180.1
41       60.0   98.0     126.0     286.0
42       60.0  100.0     122.0     329.4
43       60.0  111.0     138.0     400.0
44       60.0  111.0     131.0     397.0
45       60.0   99.0     119.0     273.0
46       60.0  109.0     153.0     387.6
47       45.0  111.0     136.0     300.0
48       45.0  108.0     129.0     298.0
49       60.0  111.0     139.0     397.6
50       60.0  107.0     136.0     380.2
51       80.0  123.0     146.0     643.1
52       60.0  106.0     130.0     263.0
53       60.0  118.0       NaN     486.0
54       30.0  136.0     175.0     238.0
55       60.0  121.0     146.0     450.7
56       60.0    NaN     121.0     413.0
57       45.0  115.0     144.0     305.0
58       20.0  153.0     172.0     226.4
59       45.0  123.0     152.0     321.0
60      210.0  108.0       NaN    1376.0
61      160.0  110.0     137.0    1034.4
62      160.0  109.0     135.0     853.0
63       45.0  118.0     141.0     341.0
64       20.0  110.0     130.0     131.4
65      180.0   90.0     130.0     800.4
66      150.0    NaN     135.0     873.4
67      150.0  107.0     130.0     816.0
68       20.0  106.0     136.0     110.4
69      300.0  108.0     143.0    1500.2
70      150.0   97.0     129.0    1115.0
71       60.0    NaN     153.0     387.6
72       90.0  100.0     127.0     700.0
73      150.0   97.0     127.0     953.2
74       45.0  114.0     146.0     304.0
75       90.0   98.0     125.0     563.2
76       45.0  105.0     134.0     251.0
77       45.0  110.0     141.0     300.0
78      120.0  100.0     130.0     500.4
79      270.0  100.0     131.0    1729.0
80       30.0  159.0     182.0     319.2
81       45.0  149.0     169.0     344.0
82       30.0  103.0     139.0     151.1
83      120.0  100.0     130.0     500.0
84       45.0    NaN     120.0     225.3
85       30.0  151.0     170.0     300.0
86       45.0  102.0     136.0     234.0
87      120.0  100.0     157.0    1000.1
88       45.0  129.0     103.0     242.0
89       20.0   83.0     107.0      50.3
90      180.0  101.0     127.0     600.1
91       45.0  107.0       NaN       NaN
92       30.0   90.0     107.0     105.3
93       15.0   80.0     100.0      50.5
94       20.0  150.0       NaN     127.4
95       20.0  151.0     168.0     229.4
96       30.0   95.0     128

In [238]:
data_load.dropna(inplace = True)
data_load

Duration  Pulse  Maxpulse  Calories
2        60.0  103.0     135.0     340.0
3        45.0  109.0     175.0     282.4
5        60.0  102.0     127.0     300.0
6        60.0  110.0     136.0     374.0
7        45.0  104.0     134.0     253.3
8        30.0  109.0     133.0     195.1
9        60.0   98.0     124.0     269.0
10       60.0  103.0     147.0     329.3
11       60.0  100.0     120.0     250.7
12       60.0  106.0     128.0     345.3
13       60.0  104.0     132.0     379.3
14       60.0   98.0     123.0     275.0
15       60.0   98.0     120.0     215.2
16       60.0  100.0     120.0     300.0
18       60.0  103.0     123.0     323.0
19       45.0   97.0     125.0     243.0
20       60.0  108.0     131.0     364.2
21       45.0  100.0     119.0     282.0
22       60.0  130.0     101.0     300.0
23       45.0  105.0     132.0     246.0
24       60.0  102.0     126.0     334.5
25       60.0  100.0     120.0     250.0
26       60.0   92.0     118.0     241.0
28       60.0  100.0     132.0     280.0
29       60.0  102.0     129.0     380.3
30       60.0   92.0     115.0     243.0
31       45.0   90.0     112.0     180.1
32       60.0  101.0     124.0     299.0
33       60.0   93.0     113.0     223.0
34       60.0  107.0     136.0     361.0
35       60.0  114.0     140.0     415.0
36       60.0  102.0     127.0     300.0
37       60.0  100.0     120.0     300.0
38       60.0  100.0     120.0     300.0
39       45.0  104.0     129.0     266.0
40       45.0   90.0     112.0     180.1
41       60.0   98.0     126.0     286.0
42       60.0  100.0     122.0     329.4
43       60.0  111.0     138.0     400.0
44       60.0  111.0     131.0     397.0
45       60.0   99.0     119.0     273.0
46       60.0  109.0     153.0     387.6
47       45.0  111.0     136.0     300.0
48       45.0  108.0     129.0     298.0
49       60.0  111.0     139.0     397.6
50       60.0  107.0     136.0     380.2
51       80.0  123.0     146.0     643.1
52       60.0  106.0     130.0     263.0
54       30.0  136.0     175.0     238.0
55       60.0  121.0     146.0     450.7
57       45.0  115.0     144.0     305.0
58       20.0  153.0     172.0     226.4
59       45.0  123.0     152.0     321.0
61      160.0  110.0     137.0    1034.4
62      160.0  109.0     135.0     853.0
63       45.0  118.0     141.0     341.0
64       20.0  110.0     130.0     131.4
65      180.0   90.0     130.0     800.4
67      150.0  107.0     130.0     816.0
68       20.0  106.0     136.0     110.4
69      300.0  108.0     143.0    1500.2
70      150.0   97.0     129.0    1115.0
72       90.0  100.0     127.0     700.0
73      150.0   97.0     127.0     953.2
74       45.0  114.0     146.0     304.0
75       90.0   98.0     125.0     563.2
76       45.0  105.0     134.0     251.0
77       45.0  110.0     141.0     300.0
78      120.0  100.0     130.0     500.4
79      270.0  100.0     131.0    1729.0
80       30.0  159.0     182.0     319.2
81       45.0  149.0     169.0     344.0
82       30.0  103.0     139.0     151.1
83      120.0  100.0     130.0     500.0
85       30.0  151.0     170.0     300.0
86       45.0  102.0     136.0     234.0
87      120.0  100.0     157.0    1000.1
88       45.0  129.0     103.0     242.0
89       20.0   83.0     107.0      50.3
90      180.0  101.0     127.0     600.1
92       30.0   90.0     107.0     105.3
93       15.0   80.0     100.0      50.5
95       20.0  151.0     168.0     229.4
96       30.0   95.0     128.0     128.2
97       25.0  152.0     168.0     244.2
98       30.0  109.0     131.0     188.2
99       90.0   93.0     124.0     604.1
101      90.0   90.0     110.0     500.0
102      90.0   90.0     100.0     500.0
103      90.0   90.0     100.0     500.4
105      30.0   93.0     128.0     124.0
106     180.0   90.0     120.0     800.3
107      30.0   90.0     120.0      86.2
108      90.0   90.0     120.0     500.3
109     210.0  137.0     184.0    1860.4
110      60.0  102.0     124.0     325.2
111      45.0  107.0     124

In [232]:
data_load.fillna("EMPTY CELL", inplace = True)
data_load

Duration       Pulse    Maxpulse    Calories
0          60.0       110.0       130.0       409.1
1          60.0       117.0       145.0       479.0
2          60.0       103.0       135.0       340.0
3          45.0       109.0       175.0       282.4
4          45.0       117.0       148.0       406.0
5          60.0       102.0       127.0       300.0
6          60.0       110.0       136.0       374.0
7          45.0       104.0       134.0       253.3
8          30.0       109.0       133.0       195.1
9          60.0        98.0       124.0       269.0
10         60.0       103.0       147.0       329.3
11         60.0       100.0       120.0       250.7
12         60.0       106.0       128.0       345.3
13         60.0       104.0       132.0       379.3
14         60.0        98.0       123.0       275.0
15         60.0        98.0       120.0       215.2
16         60.0       100.0       120.0       300.0
17         45.0        90.0       112.0  EMPTY CELL
18         60.0       103.0       123.0       323.0
19         45.0        97.0       125.0       243.0
20         60.0       108.0       131.0       364.2
21         45.0       100.0       119.0       282.0
22         60.0       130.0       101.0       300.0
23         45.0       105.0       132.0       246.0
24         60.0       102.0       126.0       334.5
25         60.0       100.0       120.0       250.0
26         60.0        92.0       118.0       241.0
27         60.0       103.0       132.0  EMPTY CELL
28         60.0       100.0       132.0       280.0
29         60.0       102.0       129.0       380.3
30         60.0        92.0       115.0       243.0
31         45.0        90.0       112.0       180.1
32         60.0       101.0       124.0       299.0
33         60.0        93.0       113.0       223.0
34         60.0       107.0       136.0       361.0
35         60.0       114.0       140.0       415.0
36         60.0       102.0       127.0       300.0
37         60.0       100.0       120.0       300.0
38         60.0       100.0       120.0       300.0
39         45.0       104.0       129.0       266.0
40         45.0        90.0       112.0       180.1
41         60.0        98.0       126.0       286.0
42         60.0       100.0       122.0       329.4
43         60.0       111.0       138.0       400.0
44         60.0       111.0       131.0       397.0
45         60.0        99.0       119.0       273.0
46         60.0       109.0       153.0       387.6
47         45.0       111.0       136.0       300.0
48         45.0       108.0       129.0       298.0
49         60.0       111.0       139.0       397.6
50         60.0       107.0       136.0       380.2
51         80.0       123.0       146.0       643.1
52         60.0       106.0       130.0       263.0
53         60.0       118.0  EMPTY CELL       486.0
54         30.0       136.0       175.0       238.0
55         60.0       121.0       146.0       450.7
56         60.0  EMPTY CELL       121.0       413.0
57         45.0       115.0       144.0       305.0
58         20.0       153.0       172.0       226.4
59         45.0       123.0       152.0       321.0
60        210.0       108.0  EMPTY CELL      1376.0
61        160.0       110.0       137.0      1034.4
62        160.0       109.0       135.0       853.0
63         45.0       118.0       141.0       341.0
64         20.0       110.0       130.0       131.4
65        180.0        90.0       130.0       800.4
66        150.0  EMPTY CELL       135.0       873.4
67        150.0       107.0       130.0       816.0
68         20.0       106.0       136.0       110.4
69        300.0       108.0       143.0      1500.2
70        150.0        97.0       129.0      1115.0
71         60.0  EMPTY CELL       153.0       387.6
72         90.0       100.0       127.0       700.0
73        150.0        97.0       127.0       953.2
74         45.0       114.0       146.0       304.0
75         90.0        98.0       125.0       563.2
76 

In [235]:
data_load.dropna(inplace = True)
data_load


Duration       Pulse    Maxpulse    Calories
0          60.0       110.0       130.0       409.1
1          60.0       117.0       145.0       479.0
2          60.0       103.0       135.0       340.0
3          45.0       109.0       175.0       282.4
4          45.0       117.0       148.0       406.0
5          60.0       102.0       127.0       300.0
6          60.0       110.0       136.0       374.0
7          45.0       104.0       134.0       253.3
8          30.0       109.0       133.0       195.1
9          60.0        98.0       124.0       269.0
10         60.0       103.0       147.0       329.3
11         60.0       100.0       120.0       250.7
12         60.0       106.0       128.0       345.3
13         60.0       104.0       132.0       379.3
14         60.0        98.0       123.0       275.0
15         60.0        98.0       120.0       215.2
16         60.0       100.0       120.0       300.0
17         45.0        90.0       112.0  EMPTY CELL
18         60.0       103.0       123.0       323.0
19         45.0        97.0       125.0       243.0
20         60.0       108.0       131.0       364.2
21         45.0       100.0       119.0       282.0
22         60.0       130.0       101.0       300.0
23         45.0       105.0       132.0       246.0
24         60.0       102.0       126.0       334.5
25         60.0       100.0       120.0       250.0
26         60.0        92.0       118.0       241.0
27         60.0       103.0       132.0  EMPTY CELL
28         60.0       100.0       132.0       280.0
29         60.0       102.0       129.0       380.3
30         60.0        92.0       115.0       243.0
31         45.0        90.0       112.0       180.1
32         60.0       101.0       124.0       299.0
33         60.0        93.0       113.0       223.0
34         60.0       107.0       136.0       361.0
35         60.0       114.0       140.0       415.0
36         60.0       102.0       127.0       300.0
37         60.0       100.0       120.0       300.0
38         60.0       100.0       120.0       300.0
39         45.0       104.0       129.0       266.0
40         45.0        90.0       112.0       180.1
41         60.0        98.0       126.0       286.0
42         60.0       100.0       122.0       329.4
43         60.0       111.0       138.0       400.0
44         60.0       111.0       131.0       397.0
45         60.0        99.0       119.0       273.0
46         60.0       109.0       153.0       387.6
47         45.0       111.0       136.0       300.0
48         45.0       108.0       129.0       298.0
49         60.0       111.0       139.0       397.6
50         60.0       107.0       136.0       380.2
51         80.0       123.0       146.0       643.1
52         60.0       106.0       130.0       263.0
53         60.0       118.0  EMPTY CELL       486.0
54         30.0       136.0       175.0       238.0
55         60.0       121.0       146.0       450.7
56         60.0  EMPTY CELL       121.0       413.0
57         45.0       115.0       144.0       305.0
58         20.0       153.0       172.0       226.4
59         45.0       123.0       152.0       321.0
60        210.0       108.0  EMPTY CELL      1376.0
61        160.0       110.0       137.0      1034.4
62        160.0       109.0       135.0       853.0
63         45.0       118.0       141.0       341.0
64         20.0       110.0       130.0       131.4
65        180.0        90.0       130.0       800.4
66        150.0  EMPTY CELL       135.0       873.4
67        150.0       107.0       130.0       816.0
68         20.0       106.0       136.0       110.4
69        300.0       108.0       143.0      1500.2
70        150.0        97.0       129.0      1115.0
71         60.0  EMPTY CELL       153.0       387.6
72         90.0       100.0       127.0       700.0
73        150.0        97.0       127.0       953.2
74         45.0       114.0       146.0       304.0
75         90.0        98.0       125.0       563.2
76 

In [19]:
Data = pd.read_csv("C:\\Users\\Admin\\Desktop\\data.csv")
Data

Duration  Pulse  Maxpulse  Calories        Date
0        60.0    NaN     130.0     409.1  17/08/2023
1        60.0  117.0       NaN       NaN  18/08/2023
2        60.0  103.0     135.0     340.0  19/08/2023
3        60.0  103.0     135.0     340.0  20/08/2023
4        60.0  102.0     148.0     406.0  21/08/2023
..        ...    ...       ...       ...         ...
164      60.0  105.0     140.0     290.8  28/01/2024
165      60.0  110.0     145.0     300.0         NaN
166       NaN  115.0     145.0     310.2  30/01/2024
167      75.0  120.0     150.0     320.4  31/01/2024
168      75.0  125.0     150.0     330.4  01/02/2024

[169 rows x 5 columns]

In [3]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  168 non-null    float64
 1   Pulse     162 non-null    float64
 2   Maxpulse  161 non-null    float64
 3   Calories  163 non-null    float64
 4   Date      159 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.7+ KB


In [23]:
Data['Date'] = pd.to_datetime(Data['Date'])
print(Data.to_string())

     Duration  Pulse  Maxpulse  Calories       Date
0        60.0    NaN     130.0     409.1 2023-08-17
1        60.0  117.0       NaN       NaN 2023-08-18
2        60.0  103.0     135.0     340.0 2023-08-19
3        60.0  103.0     135.0     340.0 2023-08-20
4        60.0  102.0     148.0     406.0 2023-08-21
5        60.0  102.0     148.0     406.0 2023-08-22
6        60.0  110.0     136.0     374.0 2023-08-23
7        45.0  104.0     134.0     253.3 2023-08-24
8        30.0  109.0     133.0     195.1 2023-08-25
9        60.0   98.0     124.0     269.0 2023-08-26
10       60.0   98.0     124.0     269.0 2023-08-27
11       60.0  100.0     120.0     250.7 2023-08-28
12       60.0  106.0     128.0     345.3 2023-08-29
13       60.0  104.0     132.0     379.3 2023-08-30
14       60.0   98.0     123.0     275.0 2023-08-31
15       60.0   98.0     120.0     215.2 2023-01-09
16       60.0  100.0     120.0     300.0 2023-02-09
17       45.0   90.0     112.0       NaN 2023-03-09
18       60.

C:\Users\Admin\AppData\Local\Temp\ipykernel_9072\3140238170.py:1: UserWarning: Parsing '17/08/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  Data['Date'] = pd.to_datetime(Data['Date'])
C:\Users\Admin\AppData\Local\Temp\ipykernel_9072\3140238170.py:1: UserWarning: Parsing '18/08/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  Data['Date'] = pd.to_datetime(Data['Date'])
C:\Users\Admin\AppData\Local\Temp\ipykernel_9072\3140238170.py:1: UserWarning: Parsing '19/08/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  Data['Date'] = pd.to_datetime(Data['Date'])
C:\Users\Admin\AppData\Local\Temp\ipykernel_9072\3140238170.py:1: UserWarning: Parsing '20/08/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  Data['Date'] = pd.to_datetime(Data['Date'])
C:\Users\Admin\AppDa

In [22]:
Data.dropna(subset=['Date'], inplace = True)
print(Data.to_string())

     Duration  Pulse  Maxpulse  Calories        Date
0        60.0    NaN     130.0     409.1  17/08/2023
1        60.0  117.0       NaN       NaN  18/08/2023
2        60.0  103.0     135.0     340.0  19/08/2023
3        60.0  103.0     135.0     340.0  20/08/2023
4        60.0  102.0     148.0     406.0  21/08/2023
5        60.0  102.0     148.0     406.0  22/08/2023
6        60.0  110.0     136.0     374.0  23/08/2023
7        45.0  104.0     134.0     253.3  24/08/2023
8        30.0  109.0     133.0     195.1  25/08/2023
9        60.0   98.0     124.0     269.0  26/08/2023
10       60.0   98.0     124.0     269.0  27/08/2023
11       60.0  100.0     120.0     250.7  28/08/2023
12       60.0  106.0     128.0     345.3  29/08/2023
13       60.0  104.0     132.0     379.3  30/08/2023
14       60.0   98.0     123.0     275.0  31/08/2023
15       60.0   98.0     120.0     215.2  01/09/2023
16       60.0  100.0     120.0     300.0  02/09/2023
17       45.0   90.0     112.0       NaN  03/0

In [24]:
print(Data.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...  
163    False
164    False
166    False
167    False
168    False
Length: 159, dtype: bool


In [27]:
print(Data.drop_duplicates())

     Duration  Pulse  Maxpulse  Calories       Date
0        60.0    NaN     130.0     409.1 2023-08-17
1        60.0  117.0       NaN       NaN 2023-08-18
2        60.0  103.0     135.0     340.0 2023-08-19
3        60.0  103.0     135.0     340.0 2023-08-20
4        60.0  102.0     148.0     406.0 2023-08-21
..        ...    ...       ...       ...        ...
163      45.0    NaN       NaN     280.9 2024-01-27
164      60.0  105.0     140.0     290.8 2024-01-28
166       NaN  115.0     145.0     310.2 2024-01-30
167      75.0  120.0     150.0     320.4 2024-01-31
168      75.0  125.0     150.0     330.4 2024-01-02

[159 rows x 5 columns]


In [28]:
Data.dropna()

Duration  Pulse  Maxpulse  Calories       Date
2        60.0  103.0     135.0     340.0 2023-08-19
3        60.0  103.0     135.0     340.0 2023-08-20
4        60.0  102.0     148.0     406.0 2023-08-21
5        60.0  102.0     148.0     406.0 2023-08-22
6        60.0  110.0     136.0     374.0 2023-08-23
..        ...    ...       ...       ...        ...
161      45.0   90.0     130.0     260.4 2024-01-25
162      45.0   95.0     130.0     270.0 2024-01-26
164      60.0  105.0     140.0     290.8 2024-01-28
167      75.0  120.0     150.0     320.4 2024-01-31
168      75.0  125.0     150.0     330.4 2024-01-02

[142 rows x 5 columns]

In [29]:
Data.drop_duplicates()

Duration  Pulse  Maxpulse  Calories       Date
0        60.0    NaN     130.0     409.1 2023-08-17
1        60.0  117.0       NaN       NaN 2023-08-18
2        60.0  103.0     135.0     340.0 2023-08-19
3        60.0  103.0     135.0     340.0 2023-08-20
4        60.0  102.0     148.0     406.0 2023-08-21
..        ...    ...       ...       ...        ...
163      45.0    NaN       NaN     280.9 2024-01-27
164      60.0  105.0     140.0     290.8 2024-01-28
166       NaN  115.0     145.0     310.2 2024-01-30
167      75.0  120.0     150.0     320.4 2024-01-31
168      75.0  125.0     150.0     330.4 2024-01-02

[159 rows x 5 columns]