In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
array = np.array([[1,2,3],[4,5,6]])
print("original array:", array)
arr = array.flatten()
print(arr)

original array: [[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [13]:
array = np.ones([5,2])
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
array = np.zeros([3,2])
print(array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [16]:
array = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(array)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [19]:
arr = [[0, 1, 2, 3, 0], [0, 5, 6, 0, 7],[11,5,9,0,0]]

array = np.count_nonzero(arr)
print(array)


9


In [18]:
x = 15
x = "hello"
print(x)

hello


In [23]:
# Write a NumPy program to test whether none of the elements of a given array are zero.

arr = np.array([0,2,4,1,6])
print("original array:", arr)

result = np.all(arr)
print(result)

print(0 in arr)

original array: [0 2 4 1 6]
False
True


In [26]:
# Write a NumPy program to test if any of the elements of a given array are non-zero

arr = np.array([0,1,0,5,9,0,4])

result = np.count_nonzero(arr)
print(result)

re = np.any(arr)
print(re)

4
True


In [28]:
# NumPy: Test a given array element-wise for finiteness (not infinity or not a Number)

a = np.array([1, 0, np.nan, np.inf])

print(np.isfinite(a))

[ True  True False False]


In [32]:
# Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

Original_List= [12.23, 13.32, 100, 36.32]

arr = np.array([[12.23,13.32,100,36.32]])
print(arr)


[[ 12.23  13.32 100.    36.32]]


In [35]:
# Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

arr = np.arange(2,11).reshape(3,3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [39]:
# Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

arr = np.zeros(10)
print(arr)

arr[6] = 11
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [40]:
#  Write a NumPy program to reverse an array (the first element becomes the last).
arr = np.array([1,2,3,4,5,6])

print(arr[::-1])

[6 5 4 3 2 1]


In [48]:
# Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern.

arr = np.ones((3,2))
print(arr)

arr = np.zeros((3,4),dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]


In [52]:
# Write a NumPy program to convert a list and tuple into arrays.

lst = [1,2,3,4,5,6,7,8]

print(np.asarray(lst))

my_tuple = ([6,7,8],[1,2,3])
print(np.asarray(my_tuple))

[1 2 3 4 5 6 7 8]
[[6 7 8]
 [1 2 3]]


In [55]:
# Write a NumPy program to append values to the end of an array.

arr = np.array([10,20,30])

arr = np.append(arr,[[40,50,60],[7,8,9]])
print(arr)

[10 20 30 40 50 60  7  8  9]


In [57]:
# Write a NumPy program to create an empty and full array.

arr = np.empty([2,3])
print(arr)

arre = np.full([3,3],6)
print(arre)

[[2.12199579e-314 2.12199579e-314 4.94065646e-324]
 [4.94065646e-324 2.12199579e-314 2.12199579e-314]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [61]:
# Write a NumPy program to test whether each element of a 1-D array is also present in a

array1 = np.array([0, 10, 20, 40, 60])
print(array1)
array2 = [0, 40]
print(array2)

print(np.in1d(array1, array2))


[ 0 10 20 40 60]
[0, 40]
[ True False False  True False]


In [71]:
# Write a NumPy program to find common values between two arrays.

array1 = np.array([[0, 10, 20, 40, 60]])
array2 = [[0, 40,50,10]]

print(np.intersect1d(array1,array2))


[ 0 10 40]


In [79]:
#  Write a NumPy program to get the unique elements of an array.

arr = np.array([1,2,3,1,5,6,2,3])

lst = list(set(arr))
print(lst)

res = np.array(lst)
print(res)
print(type(res))

[1, 2, 3, 5, 6]
[1 2 3 5 6]
<class 'numpy.ndarray'>


In [83]:
# NumPy: Find the set difference of two arrays

array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = [10, 30, 40, 50, 70]

result = np.setdiff1d(array1,array2)
print(result)

result = np.setdiff1d(array2,array1)
print(result)


[ 0 20 60 80]
[30 50 70]


In [88]:
# Write a NumPy program to sort pairs of a first name and a last name and return their indices

first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')

arr = np.sort((first_names,last_names))
print(arr)

arre = np.lexsort((first_names,last_names))
print(arre)

[['Betsey' 'Genesis' 'Lanell' 'Margery' 'Shelley']
 ['Battle' 'Brien' 'Plotner' 'Stahl' 'Woolum']]
[1 3 2 4 0]


In [91]:
# Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

x = np.array([[0, 10, 20], [20, 30, 40]])

result = x[x > 10]
print(result)

result = x > 10
print(result)


[20 20 30 40]
[[False False  True]
 [ True  True  True]]


In [95]:
# Write a NumPy program to change an array's dimension.

x = np.array([1, 2, 3, 4, 5, 6])
print(x.shape)

y = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print(y)

x = np.array([1,2,3,4,5,6,7,8,9])
x.shape= (3,3)
print(x)

(6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [100]:
# Write a NumPy program to create a 2-dimensional array of size 2 x 3 (composed of 4-byte integer elements), also print the shape, type and data type of the array.

x = np.array([[2, 4, 6], [6, 8, 10],[11,25,96],[78,96,325]])
print(x)

print(type(x))
print(x.shape)
print(x.dtype)

[[  2   4   6]
 [  6   8  10]
 [ 11  25  96]
 [ 78  96 325]]
<class 'numpy.ndarray'>
(4, 3)
int32


In [102]:
# Write a NumPy program to create another shape from an array without changing its data

x = np.array([1, 2, 3, 4, 5, 6])

print(x.reshape(3,2))
print(x.reshape(2,3))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
